### ISSUE TITLE
Alphabetical Order

### ISSUE THREAD

**Issue by phoolish** [tilfin/aws-extend-switch-roles#1]
Firstly, thanks for this awesome extension!  I know that the role history is more to show last used roles, but would it be possible to order by config file or alphabetically?

**Comment by tilfin** [comment]
Thank you. The list is basically composed of original history roles and your config roles by definition order.
If duplicated roles exists, they are excluded in the latter section. Would you write role definitions by alphabetical order in your config?

**Comment by phoolish** [comment]
I can write them that way.  We have 20+ accounts, so it is the only 'sane' way to do it.

**Comment by tilfin** [comment]
Do you need the role list without original history section or not to exclude duplicated ones?

**Comment by phoolish** [comment]
I maybe assuming incorrectly, but I assume people who use this will just populate all roles in the config file rather then using the original history section.

**Comment by tilfin** [comment]
I didn't hear the problem from the users around me. but that way is preferred by the users who evenly access each role. It's ok, I will add how to show the role list to the setting.

**Comment by tilfin** [comment]
@phoolish I shipped new version 0.2.0 that supports it.

**Comment by phoolish** [comment]
Awsome.  Worked perfectly.  One side note, and I don't know if this is the Chrome extension release process.  I had to uninstall the extension and reinstall to bump from 0.1.8 to 0.2.0.
