### ISSUE TITLE
Breaks on new Personal Health Dashboard

### ISSUE THREAD

**Issue by eric5102** [tilfin/aws-extend-switch-roles#10]
I have not investigated why yet but role filter by account breaks when accessing the new dashboard: https://phd.aws.amazon.com/phd/home#/dashboard/open-issues

**Comment by tilfin** [comment]
I confirmed it.

**Comment by tilfin** [comment]
Please re-enable this extension.

**Comment by eric5102** [comment]
Thank you for fixing this so quickly!

Eric
