### ISSUE TITLE
Cannot find the extension on Chrome Web Store

### ISSUE THREAD

**Issue by Mohitg06** [tilfin/aws-extend-switch-roles#101]
Hello,

I get 404 error when I try to download the extension  https://chrome.google.com/webstore/detail/aws-extend-switch-roles/

**Comment by tilfin** [comment]
I temporarily hide this extension on chrome store because degradation #100 is found in this current version 0.13.0.  The fixed version 0.13.1 is in review, It will be published again when the review is over. The Firefox one has already been released fixed version 0.13.1.

**Comment by Mohitg06** [comment]
Thanks again for your response

**Comment by nicwise** [comment]
Conveniently, I have it working in one profile, and not the other, so I guess one has updated. Thankfully, the working one is my work account, the one I use the most.

**Comment by sfdc-rgodishela** [comment]
@tilfin Hi, Can you please add the docs to manually load the pack for temporary use until the new version is available.

**Comment by sfdc-rgodishela** [comment]
If anyone wanted until it is available in webstore, I have a workaround.

1. `https://github.com/tilfin/aws-extend-switch-roles.git`
2. `cd aws-extend-switch-roles`
3. `./bin/build.sh`
4. Go to extensions in developer mode, Load unpacked extension, 
5. Browse to aws-extend-switch-roles -> dist -> chrome
6. add the configuration as per the documentation
7. Login AWS Console, click on your account, to see the roles as per your configuration.

**Comment by justcompile** [comment]
Make sure you copy your existing configuration first as it doesn't get copied if you use the above method

**Comment by tilfin** [comment]
@sfdc-rgodishela @justcompile Thanks!

At such time, Google's review is very slow, so please expand this zip file and use it. You can install it as the Preview version with the release version at the same.

[aws-extend-switch-roles_preview.zip](https://github.com/tilfin/aws-extend-switch-roles/files/3327891/aws-extend-switch-roles_preview.zip)

**Comment by tilfin** [comment]
The v0.13.1 has been released on Chrome Extension Store
