### ISSUE TITLE
Image url is not obeyed for the first 5 items in the list of users

### ISSUE THREAD

**Issue by zyrorl** [tilfin/aws-extend-switch-roles#111]
If a user has configured an image url for each profile, when clicking the drop down list of users, the first five profiles will display a colour instead of the image, but the extended list below that will have the images.

See below:
![image](https://user-images.githubusercontent.com/3085740/62922949-ffebfd00-bdef-11e9-9ff4-e89b4d6ea6c7.png)

**Comment by timcleaver** [comment]
Do you have "Hide original role history" set? If you don't then this extension does not render the first 5 roles, the AWS console renders them (as without this extension). Turning on that option will ensure that the images display, however, you won't get the "most recently used" 5 roles at the top.

**Comment by zyrorl** [comment]
@timcleaver I don't have it set... it would be nice given that the colour codes are obeyed by the extension that the same thing happens with images, whether role history is kept or not... (imho it's always handy to have the latest used up the top, as they will likely be what you use most)

**Comment by tilfin** [comment]
With the latest version of the specification, this issue is no longer relevant.
