### ISSUE TITLE
Parse problem with "role_name"

### ISSUE THREAD

**Issue by paulhanatroche** [tilfin/aws-extend-switch-roles#115]
In configuration, adding with "/" is not possible for the role-name.
Such as "base_account/RoleA" for "role_name"

It will break extended switch role and leads to aws console.

here is example.

[Account2-Base-RoleA]
aws_account_id = account2

[Account2-RoleA]
source_profile = Account2-Base-RoleA
role_name = base_acccount/RoleA
aws_account_id = account2
color = ff0000

**Comment by tilfin** [comment]
A **role_name** cannot contain `/`.  If you do federated login,  there is `role/user` displayed on the header of AWS MC.
