### ISSUE TITLE
Switch Role fails if there is no role history

### ISSUE THREAD

**Issue by timcleaver** [tilfin/aws-extend-switch-roles#116]
If the user doesn't have an entry in the native AWS console role history list then none of the switch role links will work. They are missing the csrf token in the form request. When a switch role link is clicked the user is sent to the 400 Bad Request page. 

A user may not have any roles in the native history list if:
- they are starting from a fresh install
- they have cleared all local data

Perhaps the configured switch role links should not be shown or shown as disabled (grayed out) if the csrf token cannot be extracted?

**Comment by tilfin** [comment]
It has already been dealt with by https://github.com/tilfin/aws-extend-switch-roles/blob/master/src/lib/content.js#L49, but the behavior of AWS MC may have changed.
