### ISSUE TITLE
Cannot switch role due to missing div

### ISSUE THREAD

**Issue by jrm2k6** [tilfin/aws-extend-switch-roles#117]
Stacktrace:

```
content.js:222 Uncaught TypeError: Cannot read property 'appendChild' of null
    at generateEmptyRoleList (content.js:222)
    at extendIAMFormList (content.js:186)
    at content.js:431
```

It looks like `awsc-login-account-section` is not available yet when calling extendIAMFromList?
@tilfin FYI It was working fine until yesterday

It doesn't seem to be happening on all pages. I can reproduce when doing it from the Cloudwatch dashboard if it is the page I am redirected to after signin in.

**Comment by tilfin** [comment]
It appears to have been a temporary problem.
