### ISSUE TITLE
Set expiration in hours

### ISSUE THREAD

**Issue by felipe1982** [tilfin/aws-extend-switch-roles#118]
Is it possible to set 8 hours expiration? My IAM roles are configured to have up to 8 hours expiration time.

**Comment by bushong1** [comment]
Bump!  @tilfin would love to see Expiration time as a setting.  1 hour always destroys my cloudwatch dashboard edits...

**Comment by tilfin** [comment]
The session duration should depend on the AWS IAM configuration. This is an matter that AESR cannot intervene in.

**Comment by bushong1** [comment]
The point of the ticket is that IAM is set to 8 hours, but the session lasts only 1 anyway

**Comment by tilfin** [comment]
If you turn off this extension and switch from original history, does it work as expected?
