### ISSUE TITLE
Roles from extension do not show up

### ISSUE THREAD

**Issue by seren** [tilfin/aws-extend-switch-roles#120]
In the latest version of Chrome (78.0.3904.108), I'm having a problem getting any roles to show up in the console drop-down menu. The only change has been the addition of a "Filter by profile name" search field".

![Screen Shot 2019-11-20 at 10 28 13 AM](https://user-images.githubusercontent.com/512022/69268373-db888500-0b83-11ea-969e-fc759a736840.png)

I've logged in as an IAM user and have added this to the configuration:
```
[profile service1]
account_id = 123456789012
role_name = service_admin

[profile service2]
account_id = 123456789013
role_name = service_admin
```

I've logged out and logged in, and cleared the cache which cleared my existing role history but didn't add services from the config. If I manually switch roles the usual way (https://signin.aws.amazon.com/switchrole), that role shows up normally.

![Screen Shot 2019-11-20 at 10 46 16 AM](https://user-images.githubusercontent.com/512022/69268374-db888500-0b83-11ea-9aac-54d461bed54c.png)

One thing I noticed (before and after clearing the cache) is an error in the console on certain services (EC2 and RDS, but not Lambda nor ECS):
```
content.js:222 Uncaught TypeError: Cannot read property 'appendChild' of null
    at generateEmptyRoleList (content.js:222)
    at extendIAMFormList (content.js:186)
    at content.js:431
```
This error disappears if the extension is disabled. I'm not sure if this could be a cause of the problem, or is a result of the list not show up.

Do you have any troubleshooting advice? Thanks.

**Comment by tilfin** [comment]
@seren AWS Account ID field name is `aws_account_id`, not `account_id`.

**Comment by nehassingh** [comment]
I am getting the same issue, No roles show up in the list.  

[default]
aws_account_id = 12344
 
[dev]
role_arn = arn:aws:iam::12345:role/IT-Admin
source_profile = default

[sandbox]
role_arn = arn:aws:iam::5786:role/IT-Admin
source_profile = default

**Comment by seren** [comment]
@tilfin Ahh, thank you. I completely missed that typo.

**Comment by seren** [comment]
@nehassingh I was able to get your config to work by changing the `aws_account_id` from a number to the account name/alias I use when logging into the console.

**Comment by seren** [comment]
I'm going to close this since my issue is resolved, but feel free to add further comments if needed.
