### ISSUE TITLE
Error handling response: ReferenceError: Sanitizer is not defined

### ISSUE THREAD

**Issue by eddgrant** [tilfin/aws-extend-switch-roles#121]
Hi there,

I recently updated my profile list and added quite a few profiles, taking my total number of profiles to 80 profiles. When I tried to save the configuration I noticed that the confirmation text did not appear. On inspection of the console I could see that the following exception was thrown:

    Error handling response: ReferenceError: Sanitizer is not defined
    at chrome-extension://jpmkfafbacpgapdghgdpembnojdlgkdl/js/options.js:175:33

Looking at that line of code I'm not sure if the block is being executed because of an error (or size issue) with my config, but I believe the fact that the `Sanitizer` has not been defined at this point in the code path is probably unintentional, hence raising this issue.

O/S: Ubuntu 19.10
Chrome Version: Version 78.0.3904.108 (Official Build) (64-bit)
Plugin version: 0.14.0

Let me know if there's any more information I can provide to help progress the issue?

Many thanks,

Edd

**Comment by tilfin** [comment]
AESR does not use Sanitizer anymore.
