### ISSUE TITLE
Request: [Firefox Containers] Assume Last Role in _this_ Container

### ISSUE THREAD

**Issue by naydichev** [tilfin/aws-extend-switch-roles#126]
I've tried using the `Automatically Assume Last Role` feature, which is pretty neat. But the configuration seems to carry over between firefox [containers](https://github.com/mozilla/multi-account-containers). 

Realistically, I want the setting to be saved _per_ container, as I assign each container to a different AWS account.

I'm not even sure if this is possible, but it [seems like](https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers#What_is_.28and_isn.27t.29_separated_between_Containers) the `LocalStorage` is separated between containers. Though I'm not sure if this is true for Extensions running in those containers.

**Comment by tilfin** [comment]
I'm sorry that this feature is difficult to maintain for me.
