### ISSUE TITLE
Read config from filesystem

### ISSUE THREAD

**Issue by hoshsadiq** [tilfin/aws-extend-switch-roles#135]
Would be nice to be able to read the config from a file. This would allow you to point this extension to your ~/.aws/config, meaning any updates only need to be done once.

**Comment by AvihaiSam** [comment]
:+1:

**Comment by svdgraaf** [comment]
I was actually thinking about creating a PR for this. The extension cannot read a file outside of itself afaik. What it can do, is read a file from it's local folder.

So if you would create a symlink from `~/.aws/config` to the extension directory (that would be `~/Library/Application Support/Google/Chrome/[profile]/Extensions/[extension_id]/[version]/.` The extension would be able to read it from there.

I'll see if I can create a PR for that feature.

**Comment by tilfin** [comment]
A limitation of the browser extension is that it cannot load the local file system in the background.
