### ISSUE TITLE
Doesn't work before I've switched manually

### ISSUE THREAD

**Issue by lukebarton** [tilfin/aws-extend-switch-roles#14]
Setting new developers up with this, I've found that the extension doesn't work until I've added a switch role manually. 

You can replicate by clearing all browser cookies and trying to use the extension. It won't work. Add a role manually through the AWS interface (Top Nav -> Switch Role -> Fill form) and the extension will start working.

**Comment by tilfin** [comment]
Yes, I have recoginzed it.
Because why required csrf token is not issued without original switch role links.
I am thinking I have to write a description somewhere about it.
But I have no idea of appropriate way for it yet.

**Comment by StyleT** [comment]
@tilfin I'm pretty sure that you can get csrf token from `AWSC.Auth.getMbtc()`

**Comment by tilfin** [comment]
Fixed at version 0.4.0
