### ISSUE TITLE
Feature request - read config from git

### ISSUE THREAD

**Issue by mlushpenko** [tilfin/aws-extend-switch-roles#152]
We have a team of several people who manage number of accounts and new accounts are added from time to time. Would be great if we could have one config in git shared across the team so everyone can receive config updates at the same time.

**Comment by ZoidBB** [comment]
How would you "notify" the browser of the need to refresh from git?

**Comment by TryTryAgain** [comment]
We are doing this using the more recently added Config Sender extension API https://github.com/tilfin/aws-extend-switch-roles#extension-api ... We used https://github.com/netguru/sync-aws-extend-switch-roles as an example project for that config sender extension and swapped out github for gitlab functionality. Although I would appreciate it being native to the aws-extend-switch-roles extension the ability to do so is already offered and works well.

**Comment by tilfin** [comment]
Yes, you can implement it as a separate app through the Config Sender API. This extension does not support it.
