### ISSUE TITLE
region no longer being used to switch role?

### ISSUE THREAD

**Issue by satnam888** [tilfin/aws-extend-switch-roles#153]
Hi, 

Recently (maybe a month or so), AWS must have changed something to stop the extension working like before.

Now, without any changes to config for 6m+, the roles switches, but always leaves whatever region was in previous role to remain so I have to select a region also to get it behave as before.  

Obviously I am using region explicitly in the config, eg:

[aaaaaa]
aws_account_id =  xxxxxxxxxxx 
role_name = yyyyyyyyy
region=eu-west-1
color = 000000

for this one - if i am in role zzzz who is eu-west-2 - switching to aaaaa doesn't also switch to region eu-west-1

Any one else have same issue?

**Comment by LordValador** [comment]
I get abad request 400 error when I add a region=xxx to my config

**Comment by TryTryAgain** [comment]
This was true for me as well, it has started working again with no changes on my end. Might have been something to do with the AWS side and their updating the UI again recently, not sure how it related but I definitely experienced it not working but now it mysteriously is working again.

**Comment by AdrianSimionov** [comment]
It seems there is a bug on AWS side, even when region is present in the URL as a GET variable ...home?region=us-east-2 the UI will not read it anymore and forward you to the right region.

I consider this is a bug on AWS side and not one for this Plugin.

PS: It sucks that without paying for support, we are not allowed to tell AWS about issues on their side. A bit unfair.

**Comment by tilfin** [comment]
merges this issue to #175
