### ISSUE TITLE
0.15 release does not install to firefox

### ISSUE THREAD

**Issue by arsirantalanc** [tilfin/aws-extend-switch-roles#159]
Hi, just attempted to update manually the newly released 0.15 version of the extension to the firefox. Firefox complained the addon extension is corrupted (offered the zip file from the release page of version 0.15).

I also unzip'ed the release file, and chose the manifest file for the firefox - this didn't change the outcome however.

**Comment by tilfin** [comment]
It's already released 4 months ago. I added only forgotten version tag.
