### ISSUE TITLE
Enhancement request: open add-on with keyboard shortcut

### ISSUE THREAD

**Issue by axeleroy** [tilfin/aws-extend-switch-roles#162]
**Context:** Version 2 of the add-on has moved the account-switching UI in its [popup](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups).

It would be extremely useful to be able to open the popup using keyboard shortcuts, allowing to quickly switch accounts.

**Comment by tilfin** [comment]
You can set the shortcut in `chrome://extensions/shortcuts`.

**Comment by axeleroy** [comment]
Yes, but you can't on Firefox unless shortcuts have been defined in the manifest.

**Comment by tilfin** [comment]
I see.
