### ISSUE TITLE
Unable to change Font Color

### ISSUE THREAD

**Issue by SamHkp19** [tilfin/aws-extend-switch-roles#165]
Hi There,

Once again a big thanks for the plugin and the regular updates.

I am finding a feature missing that I required the BG color option is available but the font color change option is not available.

Can this be implemented, 

The reason is when I change my BG to blend it with the original color which is dark bluest black on the top bar, I cannot see the font or the font is not visible anymore as the default font is black, so when I wanted to change to the white font I am not getting that options.

I am attaching the screenshot for your reference highlighted in red marker.
![image](https://user-images.githubusercontent.com/10721146/94335347-b614a500-fff8-11ea-8949-88735d007a69.png)

It would be very much great if that feature is added, thanks in advance

Thanks
Sam

**Comment by michaelm88** [comment]
Hi 
i am using firefox and SSO and and it is nor working 
![image](https://user-images.githubusercontent.com/44439016/94422407-f1d97700-017e-11eb-9079-72b909b06c66.png)

**Comment by duttonw** [comment]
AWS just did a major revamp of their console, which sucks :'( hope this extension can get ahead of it :).  Might be time for us to chip in on how good it is :)

**Comment by tilfin** [comment]
reverted to adjust the font color against the specified background-color at v2.0.4
