### ISSUE TITLE
Plugin appears to not be working at all after update to 2.0.3

### ISSUE THREAD

**Issue by roboweaver** [tilfin/aws-extend-switch-roles#166]
Just got the update notice for 2.0.3 and now none of my roles are appearing in the dropdown.

The prior version was working (although the colors weren't matching the change that AWS made to the list being dark mode, so was hoping this would fix that issue.)

I have a config file with our 150+ accounts in it with the basic format:

```
[wf-foobar]
role_arn = arn:aws:iam::999999999999:role/fakerole
color = FF8080
```

**Comment by roboweaver** [comment]
Never mind, figured it out - the wording of the update wasn't very clear on what the breaking change actually meant.

Instead of using the dropdown as before, clicking on the `aws-extend-switch-roles` extension icon (which I had to move to where I could see it) gives the list of accounts as before.

Before it was in the page:

![Screen Shot 2020-09-26 at 9 01 07 AM](https://user-images.githubusercontent.com/3752123/94344086-2829c180-ffda-11ea-9357-551f3ab8bae5.png)

After it is not:

![Screen Shot 2020-09-26 at 9 13 13 AM](https://user-images.githubusercontent.com/3752123/94344088-2a8c1b80-ffda-11ea-930f-eaa007f34865.png)

**Comment by jtstrohl** [comment]
@roboweaver - I just went through the same discovery process.... Thanks for sharing the solution for others.

@tilfin - You, sir, are my hero...  Thank you (and other contributors) for your work on this extension, which has changed my life.  I'll be throwing a donation your way, and I'd suggest others to do the same if this extension adds value for you.
