### ISSUE TITLE
Background colour of the extension is black

### ISSUE THREAD

**Issue by yuvalek** [tilfin/aws-extend-switch-roles#168]
Hi, 

First I want to say thank you for this wonderful extension.
Second, could you please add "background-color: #fafafa;" under the body in popup.html?
https://github.com/tilfin/aws-extend-switch-roles/blob/99ca279bc8ce0f51c51dbfe0ddd6352269290b91/popup.html#L5
The reason I want it is because i'm using opera with dark theme and that causes the extension to be black.
This change make it white.

Thanks!

**Comment by tilfin** [comment]
Why does the color is expected `#fafafa` not `#ffffff`?

**Comment by yuvalek** [comment]
You are right #ffffff is better.

**Comment by tilfin** [comment]
@yuvalek  Please confirm the issue that has been fixed at v2.0.4.

**Comment by yuvalek** [comment]
It is fixed Thanks!
