### ISSUE TITLE
'Show only matching roles' does not work in 2.0.4

### ISSUE THREAD

**Issue by teodor-kostadinov** [tilfin/aws-extend-switch-roles#174]
Hi guys,

Is it just me or Show only matching roles is not working for other people too? 

Here is our very simplified config.
`[Hub-Account]
aws_account_id = hub-account-alias

[Account1-Role1]
aws_account_id = account-1-alias
role_arn = arn:aws:iam::<account1id>:role/Role1
source_profile = Hub-Account
color = ff80ff

[Account1-Role2]
aws_account_id = account-1-alias
role_arn = arn:aws:iam::<account1id>:role/Role2
source_profile = Hub-Account
color = ff80ff
`

However, when I log in to Account1 using Role 1, I can still see Role 2 listed there
![image](https://user-images.githubusercontent.com/52125950/94894968-6a2e8980-0458-11eb-8d89-4703c914d5a6.png)

I have also tried using role_name attribute instead of role_arn, the same thing. 

Any help is appreciated. Thanks!

**Comment by timschill** [comment]
You can close this issue, somehow I had managed to change source_profile into just source.

**Comment by tilfin** [comment]
I had made a mistake. I'll fix it in the next version.

**Comment by teodor-kostadinov** [comment]
@tilfin Unfortunately I still get the same behavior in 2.0.5.  I have tried role_arn , role_name etc in my target profiles but I am still seeing all roles listed.

Here is a sanitized example of my config

`
[master]
aws_account_id = master-account-alias

[target-role1]
aws_account_id = target-account-alias
role_name = role1
source= master

[target-role2]
aws_account_id = target-account-alias
role_name = role2
source= master
`

**Comment by teodor-kostadinov** [comment]
Ignore me. Uninstalling the plugin and re-adding the config fixed it for me. All set.

Thanks for your great work! :)

**Comment by evandam** [comment]
I just uninstalled and reinstalled the plugin but it doesn't seem to be working for me. I'm ont 2.0.5 as well.

**Comment by scalp42** [comment]
Same here I can confirm. It just lists all the roles defined in the config even if you can't assume them.\
