### ISSUE TITLE
Parsing error: source_profile =

### ISSUE THREAD

**Issue by nskitch** [tilfin/aws-extend-switch-roles#22]
My AWS config file contains the source_profile directive. Rather than copying and pasting, I have to manually remove this line else aws-extend-switch-roles fails to import

Great extension!

would also like a bit more customizability surrounding highlighting color for accounts

**Comment by tilfin** [comment]
I cannot detect a bug about parsing source_profile.
Can you submit an example? if it contains sensitive captions, please replace them by something strings.

**Comment by fir3wall** [comment]
Hi,
Also not working for me, this is my config (I've got multiple of entries like this one with source_profile).

`[default]
aws_account_id = xxxxxxxxxxxx
[profile uk-hosted-live]
role_arn = arn:aws:iam:zzzzzzzz:role/Role_Name
source_profile = default
`

**Comment by tilfin** [comment]
@fir3wall Do you use an alias of AWS Account? if you use it, please replace aws account id digits with the alias.

**Comment by tilfin** [comment]
Timeout
