### ISSUE TITLE
manage pinned items per profile

### ISSUE THREAD

**Issue by kisst** [tilfin/aws-extend-switch-roles#27]
Use-case, different profiles has different AWS services used, there for different pinned items can be handy, also as it depends on cookies, new sessions etc can wipe it clean.
The pinned items are stored under the cookie named `noflush_awscnm` for the domain `.console.aws.amazon.com`, and it contains a html encoded json object with the following structure.

```
{
  "hist": [
    "home"
  ],
  "sc": [
    "cfo",
    "cfg",
    "ec2"
  ],
  "tm": "tm-both",
  "ea": true
}
```

Where the `hist`, control the dashboard history items, the `sc` the pinned items on the top of the console, but not sure about the `tm` and `ea`.

The format can be something like:
```
[profile marketingadmin]
role_arn = arn:aws:iam::123456789012:role/marketingadmin
source_profile = default
color = FFF933
sc = cfo,cfg,ec2,etc
```

Might not needed to modify the `hist`, and the `tm`/`ea` but only the `sc`, so at the time of switch, decode the existing value of the cookie, modify the `sc` section encode it and write it back.

**Comment by tilfin** [comment]
This is a severe problem because it expands this application domain.
I do not want to follow the changes in AWS Managment console as possible.
If I can deal with something, it will support a hook script in _after switch_.

**Comment by RichardBronosky** [comment]
> This is a severe problem because it expands this application domain.
> I do not want to follow the changes in AWS Managment console as possible.
> If I can deal with something, it will support a hook script in _after switch_.

Did you ever make any progress on the "support a hook script in _after switch_" idea? I'd like to give some non-technical people access to limited roles and include a link directly to download invoices, or upload to a specific S3 bucket folder/prefix. A hook would empower this.

**Comment by RichardBronosky** [comment]
@tilfin 

> This is a severe problem because it expands this application domain.
> I do not want to follow the changes in AWS Managment console as possible.
> If I can deal with something, it will support a hook script in _after switch_.

Did you ever make any progress on the "support a hook script in _after switch_" idea? I'd like to give some non-technical people access to limited roles and include a link directly to download invoices, or upload to a specific S3 bucket folder/prefix. A hook would empower this.
