### ISSUE TITLE
Roles don't appear

### ISSUE THREAD

**Issue by crptz** [tilfin/aws-extend-switch-roles#292]
**Describe the bug**
Hi, we are 3 people working with the same config and mine doesn't work while theirs it's working perfectly.
I have tried to clear cache, update chrome, restart computer, remove and re-add extension and what ever else

**Expected behavior**
I expected the roles to appear so I can switch to them. While I have added the config (exactly the same as my friend's) it does not work, it doesn't show the roles to switch when I am at aws console. I have also tried with only one profile in case there was a syntax error but still nothing.

**Environment**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [114.0.5735.134]

**Additional context**
I have also tried on firefox and it wasn't working there either. We've checked it many times with my friends together but there is no luck.

Cheers !

**Comment by Andrwe** [comment]
This happened to me on Mozilla Firefox 114.0.2 too.
I could solve it by replacing all occurrences of `source_profile` in the configuration.
It seems like every profile that either uses `source_profile` or is targeted by `source_profile` is removed from the list of available profiles.

**Comment by tilfin** [comment]
@unavoidable0100 Do you have checked "Show only matching roles" in Settings? Try unchecking that box.

**Comment by JakeJeffreys** [comment]
Im experiencing the same issue in Chrome version 115.0.5790.114 and Extension version 3.0.0.

Any profile that uses `source_profile` is ignored from the list. "Show only matching roles" is unchecked. I can fix by removing all of the `source_profile` fields and manually adding that information into each profile but I'd rather not.

Seems like a pretty valid `source_profile` bug.

**Comment by takobaba** [comment]
I started to experience the same issue when the extension auto updated itself to version 4. I fixed the issue by just making a dummy change on the config and saving. After I clicked save I went back on the AWS console and I was able to list the roles.
