### ISSUE TITLE
syntax error on readme page

### ISSUE THREAD

**Issue by douglasheld** [tilfin/aws-extend-switch-roles#30]
On the readme page on Github, the example:

````
[baseaccount1]
aws_account_id = 000000000000

[targetaccount1]
<snip>

[baseaccount2]
aws_account_id = your-alias-name
````

is missing the '**profile**' keyword. Should be:
````
[profile baseaccount1]
aws_account_id = 000000000000

[targetaccount1]
<snip>

[profile baseaccount2]
aws_account_id = your-alias-name
````

**Comment by tilfin** [comment]
It's not mistakes. It could be loadded with or without prefix `profile`.
This extension supports the setting format like `~/.aws/config`  or `~/.aws/credentials`.
The section caption of `~/.aws/config` is with `profile` prefix.
The section caption of `~/.aws/credentials` is without `profile` prefix.
so I wrote their examples as it is deliberately.
