### ISSUE TITLE
Specify region when switching role

### ISSUE THREAD

**Issue by JChrist** [tilfin/aws-extend-switch-roles#31]
Hello.
I was wondering if it would be possible to specify a region to go by default for a specified role.
I know this isn't possible from the default AWS role switcher, but perhaps there's some parameter to use in order to make this possible (e.g. the redirect_uri ?).

So, I could set that when switching to a specific role, I would directly go to a specific region, not the region I was before switching to the role.
Something along the following lines, where clicking on the Staging role would switch to the role and directly select the eu-west-1 region:
[Staging]
aws_account_id = 11223344556677
role_name = staging
color=787878
region=eu-west-1

**Comment by tilfin** [comment]
After examining it for a moment, I noticed that the input redirect_uri values are replaced with current console region when opening a popup.
It seems to be a bothersome change.

**Comment by JChrist** [comment]
I'm not sure whether this helps, but I was in eu-west-1 region and the redirect_uri hidden input for a role contained the following value:
`https%3A%2F%2Feu-west-1.console.aws.amazon.com%2Fconsole%2Fhome%3Fregion%3Deu-west-1%23`

while I would prefer it to switch directly to ap-southeast-1. So, I changed the value to:
`https%3A%2F%2Fap-southeast-1.console.aws.amazon.com%2Fconsole%2Fhome%3Fregion%3Dap-southeast-1%23`

and it worked as expected: switched to the selected role in my preferred region.

**Comment by tilfin** [comment]
Please tell me in a bit more detail. What timing do you rewrite the value of `redirect_uri` ?
I wonder that it executes at the timing to trigger the submit event of the form.

**Comment by JChrist** [comment]
I've only done it through the inspector (in the dev tools), right after opening the menu containing the roles and I clicked on the role after modifying it (I didnt close the menu)

**Comment by tilfin** [comment]
Yes, if you close and open the menu after that, the redirect_urls will be reverted.

**Comment by tilfin** [comment]
released v0.7
