### ISSUE TITLE
Paste with non-qwerty keyboard fails - closes panel immediately

### ISSUE THREAD

**Issue by rdunlop** [tilfin/aws-extend-switch-roles#34]
I use dvorak as my keyboard layout.

When I open the extension and Command-V paste the contents I want into the panel, it immediately closes the panel, and does not work.

BTW, `Command-v` in dvarak is `Command-.` on the keyboard.

I have tried this even in an incognito window with only minimal other extensions running, same behavior is observed.

**Comment by tilfin** [comment]
Timeout

Anyone can reopen this if encounters the same issue.
