### ISSUE TITLE
Restrict showing Role List for IAM user.

### ISSUE THREAD

**Issue by richard-scott** [tilfin/aws-extend-switch-roles#36]
I have an IAM user called "richard.scott" in an AWS account with an ID of 123456789012.
When I log into that IAM account I am unable to show a restricted list of Roles sepcific to that user/account combination.

I have tried the following:

```
[MyAccount]
aws_account_id = richard.scott@123456789012

[profile Marketing]
role_arn = arn:aws:iam::123456789012:role/marketingadmin
source_profile = MyAccount
```

If I untick "Show only matching roles" i get to see ALL roles configured which is not what I want.

How can I do this? Is there an example as I could not find one.
The examples all seem to assume you are logging in with the root username which is bad practice.

**Comment by tilfin** [comment]
The value of `aws_account_id` doesn't contain your username, must be only AWS Account ID.
```
[MyAccount]
aws_account_id = 123456789012
```

The "Show only matching roles" option is federated AWS login.  I consider to rename this because it is to be confused surely.

**Comment by richard-scott** [comment]
ok, thanks for clearing that up.
