### ISSUE TITLE
Setting an 'external_id' for a role

### ISSUE THREAD

**Issue by richard-scott** [tilfin/aws-extend-switch-roles#37]
Is there a way to set the "external_id" configured on a role?
I've searched the source code but can't find anything.

**Comment by tilfin** [comment]
@richard-scott The `external_id` does not support switching role on AWS management console.

> Switching roles using the AWS Management Console works only with accounts that do not require an ExternalID. 

in https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html

**Comment by richard-scott** [comment]
ok, thanks for the details.
