### ISSUE TITLE
Roles don't show up (solution found)

### ISSUE THREAD

**Issue by richard-scott** [tilfin/aws-extend-switch-roles#38]
I've just had a user who I gave my "role" config to. They cut-and-paste'd it into the Chrome Extnesion and then proceeded to log into the AWS Console.

After login, they had no roles. I since found out that **aws_account_id** needs to be set to the same text/numbers used when entering your login credentials on the AWS console login form.

Once we changed this in the extensions config, they roles appeared.

**Comment by tilfin** [comment]
I think that has already been mentioned on the Complex Configuration of README.
