### ISSUE TITLE
Increase maximum profile

### ISSUE THREAD

**Issue by tmor** [tilfin/aws-extend-switch-roles#52]
Firstly, thank you for useful extension.

Issue type
---

Feature request

What problem does this feature solve?
---

Maximum profile is about 40.
Beyond that, the role does not increase.
I would like to add about 100 profiles.

Version: 
---

- AWS Extend Switch Roles: 0.8.0
- Chrome 65.0.3325.181

Steps to reproduce
---

1. Open Configuration
2. Add profiles
```
[profile base]
output = json
region = ap-northeast-1
aws_account_id = 000000000000

[profile dev-readonly]
output = json
region = ap-northeast-1
role_arn = arn:aws:iam::100000000000:role/role-readonly
source_profile = base
color = B7CA9D
...
```
3. Save
4. Refresh browser

**Comment by tilfin** [comment]
The sync storage size limitation of Chrome extension causes this problem.

**Comment by Hount** [comment]
Is there a way to go around this? e.g. disable Chrome extension sync?

**Comment by thor-ni** [comment]
Is it possible to separate the profiles into categories to limit what profiles are visible at a single time?, or have the extension read from a config file stored in the cloud or locally?

**Comment by roboweaver** [comment]
I found an example of a workaround for the storage limit in Chrome - clearly it's not a complete solution, but it could extend the size of the data that could be stored locally: https://github.com/kdzwinel/Context/blob/master/js/classes/HugeStorageSync.class.js

The class allows you to store multiple QUOTA_BYTES_PER_ITEM  size items.

**Comment by Hount** [comment]
Same plugin works on Firefox, that was my solution.

**Comment by TryTryAgain** [comment]
Experiencing this same issue, needing to have many accounts/profiles. Firefox is working as a workaround, thanks @Hount, but I'd love to have this working in Chrome.

**Comment by ablackburnTurner** [comment]
> Same plugin works on Firefox, that was my solution.

Only thing about firefox is, you don't seem to be able to Ctrl+F to find items in the drop down quickly.

**Comment by tilfin** [comment]
New verion 0.9.0 supports up to 200 profiles.
