### ISSUE TITLE
The add-on fails to parse source profile references

### ISSUE THREAD

**Issue by tagirb** [tilfin/aws-extend-switch-roles#53]
If I paste an `~/.aws/config` with some source profile references, the add-on stops working. If I filter these references away, it starts working. Is it really necessary to use source profile references?

Thanks a lot for this useful plugin!

**Comment by tilfin** [comment]
I'm sorry, `source_profile = default` must not be defined. 
I will erase `~/.aws/config` link from the configuration with the next version because it is confusing.

**Comment by tagirb** [comment]
Is it possible to just skip/ignore the `source_profile` references? I have ~15 accounts and likely will have more, so it's a bit tedious to remove the `source_profile` definitions every time I update the config.
