### ISSUE TITLE
Safari Support

### ISSUE THREAD

**Issue by gaurish** [tilfin/aws-extend-switch-roles#54]
Any interest in adding support for safari? I have chrome but safari much better at battery on mac.

**Comment by tilfin** [comment]
I am sorry, but I have no energy to support safari.

**Comment by tvb** [comment]
@tilfin how are you on energy today?

**Comment by jessebye** [comment]
This might be possible now with Safari Web Extensions: https://developer.apple.com/documentation/safariservices/safari_web_extensions

**Comment by rmatec** [comment]
Hey @tvb @jessebye,
I've ported this plugin to Safari and the extension is published in the Mac Store. More info here https://github.com/rmatec/aws-account-switcher-safari-extension

**Comment by tvb** [comment]
BAM! Very nice @rmatec I've installed the extension and will give it a try 👍🏻
