### ISSUE TITLE
Show Only matching roles bugs

### ISSUE THREAD

**Issue by joalcorn** [tilfin/aws-extend-switch-roles#55]
Two issues occur when "Show only matching roles" is checked.

1. If multiple entries for the same account, but with different roles appear in the config, then only the last defined entry will be displayed.
2. If using SAML federation into the base account, no roles show up regardless of whether you use the account alias or account ID for the aws_account_id paramter in the configuration.

**Comment by 1oglop1** [comment]
I just experienced same issue with `2.`

**Comment by tilfin** [comment]
I guess that your 'Federated Login' and 'Account ID' that contain unexpected character about issue `2. `

**Comment by tilfin** [comment]
I guess that the issue `1.` has been fixed by #58 .

**Comment by tilfin** [comment]
The issue of `2.` is merged in #136.
