### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by phoolish** [tilfin/aws-extend-switch-roles#6]
I believe AWS updated the Management Console code and I am no longer seeing the list of roles.  I'm working with Chrome Version 54.0.2840.71 (64-bit) on a mac. I've included 2 screen shots below and I've blacked out the roles/IAM user name for security purposes.

The first display is when I've disabled "Hide original role history"
<img width="251" alt="screen shot 2016-11-23 at 11 03 30" src="https://cloud.githubusercontent.com/assets/160523/20571530/7157362c-b16d-11e6-9f7c-74ebd0363d25.png">

The second is with "Hide original role history" enabled
<img width="256" alt="screen shot 2016-11-23 at 11 03 47" src="https://cloud.githubusercontent.com/assets/160523/20571531/715d3ebe-b16d-11e6-8c25-1bb01b307a2a.png">

**Comment by eric5102** [comment]
It works fine on Chrome/Windows

Did you enter a configuration? and did you set the aws_account_id=tablexi? It  filters out all roles you configured that do not belong to the account you are currently logged in so your configuration should look something like this:

```
[tablexi]
aws_account_id = tablexi

[profile XXX]
role_arn = arn:aws:iam::0123456789:role/your_role
source_profile = tablexi
color=66FF66

...more profiles...
```

The source_profile must be set to the aws_account_id

**Comment by phoolish** [comment]
The tablexi entry got removed some how.  Thanks for the help.

![image](https://cloud.githubusercontent.com/assets/160523/20573220/686868cc-b174-11e6-964d-69d5eb460c3a.png)
