### ISSUE TITLE
No longer see my configuration in the Configuration Panel

### ISSUE THREAD

**Issue by rberger** [tilfin/aws-extend-switch-roles#66]
Everything is working fine, but if I go to the Configuration Tab, I don't see my configuration. I've been using this most excellent extension for a long time without changing the config. 

Could it have not been copied over when things switched from the old pop-up to new tab mechanism?

**Comment by tilfin** [comment]
I changed the way to store .ini style configuration for #52. It almost causes your configuration to be disappeared. This extension has .ini text and structure profile data separately. So the .ini configuration is stored for only next editing. The profile data is updated on pressing save button.
To be resolved, please paste the your .ini configuration into the textbox again!

**Comment by dessite** [comment]
And where Can i find this ini configuration? I also have empty text area in config but am still able to switch previously saved roles

**Comment by tilfin** [comment]
Please save something change after updating to version 0.11.0, therefore clearing some profiles remaing.
