### ISSUE TITLE
No longer see my configuration in the Configuration Panel

### ISSUE THREAD

**Issue by rberger** [tilfin/aws-extend-switch-roles#67]
Everything is working fine, but if I go to the Configuration Tab, I don't see my configuration. But it clearly has the configuration when I use the switcher. If I disable the extension the switcher no longer shows my setup. And when I re-enable it, my setup is correct.

I've been using this most excellent extension for a long time without changing the config. 
Could it have not been copied over when things switched from the old pop-up to new tab mechanism?

**Comment by tilfin** [comment]
duplicate #66
