### ISSUE TITLE
Ghost entries in config

### ISSUE THREAD

**Issue by pberswe** [tilfin/aws-extend-switch-roles#70]
I have ghost entries in my configuration, even if i remove all entrys in the extension configuration and save it i still have some entrys left in the list, where can these be stored?

(the dot is there to show empty list)

~/.aws/config contains only Profile name and region entry
[profile sfxxxxx]
region = eu-west-1
[profile xxxxteam]
...

<img width="544" alt="screenshot 2018-12-18 at 14 55 31" src="https://user-images.githubusercontent.com/26113833/50158815-6c504400-02d5-11e9-9113-ef5a85a11e42.png">
<img width="62" alt="screenshot 2018-12-18 at 14 56 02" src="https://user-images.githubusercontent.com/26113833/50158823-707c6180-02d5-11e9-85db-e7841a46901e.png">

**Comment by SamHkp19** [comment]
Hi There,

I too have a similar query, but slightly different.

I need to clear all my existing entries and add new fresh entries when going to the config I could not see any of the list at all and it is shown blank But I can see the old list still in the role history.

It would be very great if we have an option to clear out the existing and add new ones.

I thought that options were there in the older version but now that seems to be not there anymore.

Please add that features again.

Thanks
Sam

**Comment by rekahsoft** [comment]
Does anyone know how to remove these ghost entries? Within `~/.mozilla/firefox/<PROFILE>/browser-extension-data/aws-extend-switch-roles@toshi.tilfin.com` there are no files. Additionally, when the extension is remove and re-installed, the problem persists. The only workaround I've found for this is using a new firefox profile.

**Comment by tilfin** [comment]
Please save something change after updating to version 0.11.0, therefore clearing some profiles remaing.

**Comment by rekahsoft** [comment]
@tilfin perfect! After upgrading to version 0.11.0 and saving my config again, this issue has been resolved! :)
