### ISSUE TITLE
Roles Missing, Configuration Errors? Matching Roles w/ Multiple Base Accounts

### ISSUE THREAD

**Issue by jwshields** [tilfin/aws-extend-switch-roles#71]
Hello,

I believe I've run into an issue with this extension regarding mutliple base roles, the filtering, and assuming different roles;
Also, I believe that this may be related to #55 in some form.
The environment I'm in is a bit complex, I will attempt to do my best to explain it-

Info:
Ext Version: 0.10.1
Browser: Chrome 72.0.3626.64

Problem:
I am a user at an org which uses an IDP for SSO/SAML/Federated auth/login, I can log into multiple roles in multiple AWS accounts, and those roles have permissions which allow the assuming of other roles, when I attempt to configure this extension to work for me, it appears to break and does not show any roles.

----

My IDP allows the selection of login to two separate AWS "apps"/tiles/buttons/accounts
Me -> IDP -> "AWS Account 1" OR "AWS Account 2"

If I log into "AWS Account 1" I will be signed into AWS as "acct1rolename/My.Email@company.com" on account "AWS Account 1"

If I log into "AWS Account 2", it logs me in to the AWS console, the console then presents me with two options of which role to act as, "RoleA" or "RoleB" - clicking either will log me into AWS as "Role[A|B]/My.Email@company.com" on account "AWS Account 2"
If I am using "RoleA" - I am able to assume "RoleA" on "AWS Account 2", "RoleA" on "AWS Account 3", and "RoleA" on "AWS Account 4"
If I am using "RoleB" - I am able to assume "RoleB" and "RoleC" on "AWS account 2", "AWS Account 3", and "AWS Account 4"

----
I've attached a small image to sort of help illustrate what I'm meaning by this.
![image](https://user-images.githubusercontent.com/7400556/51771648-8a604f80-209e-11e9-9f11-ba364c906ceb.png)

This is my current config, in a somewhat redacted form.
```
[Account1-Base]
aws_account_id = account1
color = 00c100

[Account2-Base-RoleA]
aws_account_id = account2

[Account2-Base-RoleB]
aws_account_id = account2


[Account2-RoleA]
source_profile = Account2-Base-RoleA
role_name = RoleA
aws_account_id = account2
color = ff0000

[Account3-RoleA]
source_profile = Account2-Base-RoleA
role_name = RoleA
aws_account_id = account3
color = ff8000

[Account4-RoleA]
source_profile = Account2-Base-RoleA
role_name = RoleA
aws_account_id = account4
color = 006cd9


[Account2-RoleB]
source_profile = Account2-Base-RoleB
role_name = RoleB
aws_account_id = Account2
color = ff0000

[Account2-RoleC]
source_profile = Account2-Base-RoleB
role_name = RoleC
aws_account_id = Account2
color = ff0000

[Account3-RoleB]
source_profile = Account2-Base-RoleB
role_name = RoleB
aws_account_id = Account3
color = ff8000

[Account3-RoleC]
source_profile = Account2-Base-RoleB
role_name = RoleC
aws_account_id = Account3
color = ff8000

[Account4-RoleB]
source_profile = Account2-Base-RoleB
role_name = RoleB
aws_account_id = Account4
color = 006cd9

[Account4-RoleC]
source_profile = Account2-Base-RoleB
role_name = RoleC
aws_account_id = Account4
color = 006cd9
```

How can I set up the extension to follow this flow?
Thank you in advance if I am missing anything obvious or breaking my config somehow.

**Comment by tilfin** [comment]
@jwshields **aws_account_id** must be defined on base account (ex. Account1-Base) entries, not on target role entries (ex. Account2-RoleA).  A entry cannot have both **aws_account_id** and **source_profile** at the same.

**Comment by tilfin** [comment]
I'm sorry that the complex configuration example is wrong!

**Comment by tilfin** [comment]
@jwshields It was wrong that I commented early, so I erased it. I am investigating the extension behavior on mutiple roles of fedelation login.

**Comment by jwshields** [comment]
Thank you very much!

As another note, I tried another config with something separate but that did not seem to work either.
If I filter for matching roles, it only shows the role that I assumed when logging into account 2 and not the other (ie, role b only versus role b & c)


```
[Account1-Base]
aws_account_id = account1
color = 00c100

[Account2-Base]
aws_account_id = account2


[Account2-RoleA]
source_profile = Account2-Base
role_name = RoleA
aws_account_id = account2
color = ff0000

[Account3-RoleA]
source_profile = Account2-Base
role_name = RoleA
aws_account_id = account3
color = ff8000

[Account4-RoleA]
source_profile = Account2-Base
role_name = RoleA
aws_account_id = account4
color = 006cd9


[Account2-RoleB]
source_profile = Account2-Base
role_name = RoleB
aws_account_id = Account2
color = ff0000

[Account2-RoleC]
source_profile = Account2-Base
role_name = RoleC
aws_account_id = Account2
color = ff0000

[Account3-RoleB]
source_profile = Account2-Base
role_name = RoleB
aws_account_id = Account3
color = ff8000

[Account3-RoleC]
source_profile = Account2-Base
role_name = RoleC
aws_account_id = Account3
color = ff8000

[Account4-RoleB]
source_profile = Account2-Base
role_name = RoleB
aws_account_id = Account4
color = 006cd9

[Account4-RoleC]
source_profile = Account2-Base
role_name = RoleC
aws_account_id = Account4
color = 006cd9
```

**Comment by 1oglop1** [comment]
I have similar problem as well, my config contains 10 roles where 5 belong to 1 family and another 5 to different family (with federated login) but for some reason I always see only first half. and never second even though I'm logged out

**Comment by tilfin** [comment]
@jwshields  **Show only matching roles** is to filter target roles to only those with the same name as the source role.
So if you log into RoleB of Account2, the role list should have only Account3-RoleB and Account4-RoleB rightly. Account2-RoleA and Account2-RoleB should not be defined because those are logging-in targets directly.
But I guess that you want the role list to show the target roles for each base role of Account2, so I think about the feature to classify target roles by the base account entry with role_name for federated login.

@1oglop1 Please tell me about the two _Federated Login_ values and your configuration entries that you replace by false values

**Comment by jwshields** [comment]
If it's reasonable, I'd like to request a feature, either similar to or the same as the filter roles which would show target accounts of a base account - that don't have matching names.
As it stands right now if I only declare account 2 base and then use role a b and c off of that, if I filter it only shows role a no matter whether I'm a or b

**Comment by 1oglop1** [comment]
@tilfin Thanks I got most of it working
`org2` shows correctly, however federated login is still somehow buggy

I  tested few options:
- [x] Hide original role history
- [] Hide account id
- [X] Show only matching roles
- [] Automatically assume last assumed role (Experimental)

Result: 
Login to `org1` federated acc.
`org2` - is not showed (expected)
Federated account `org1` does not show child account. (unexpected)
Login to `org2`
`org2` - is showed (expected)
Federated account `org1` is not showed. (expected)


Scenario 2
- [x] Hide original role history
- [] Hide account id
- [] Show only matching roles
- [] Automatically assume last assumed role (Experimental)

Result: 
Login to `org1` federated acc.
`org2` - is not showed 
Federated account `org1` shows child account.
Login to `org2`
`org2` - is showed (expected)
Federated account `org1` is not showed.

**Comment by tilfin** [comment]
@1oglop1 Scenario 2 is working as expected, isn't it? It's right. *Show only matching roles* means that assumed target roles that equals to your role of Federated Login are only shown. So if the role of *org-aws-labs-PD*'s role_arn is `arn:aws:iam::<accountId>:role/LabUser`, it is shown to match with **LabUser**.
