### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by eViMaN** [tilfin/aws-extend-switch-roles#74]
Hello, As of today I get HTTP error 400 when trying to switch role, while the "manual" switch role still works.
There might be some change in AWS, because the errors refers to an "old-link" 

You are aware of these issues?

**Comment by eViMaN** [comment]
Leave it.. it's already gone.. maybe an hickup anywhere in the STS service .. :-(

**Comment by arnuschky** [comment]
I am seeing this from time to time too. No idea how to get around it.

**Comment by arnuschky** [comment]
Most importantly I can't switch back to my root account or log out. I am stuck.

**Comment by eViMaN** [comment]
might be related to caching.  Did you try to clear cache and see if the issues stays ?

**Comment by arnuschky** [comment]
I did and it went away. With my toolbar config. :\

I experience this from time to time (like ever few weeks). Usually it goes away by switching to the root account or forcing a logout. This time, none of this works.

In anyone else experiencing this regularly? I wonder what is causing this.

**Comment by arnuschky** [comment]
Note to self: if you encounter this in the future, delete cookies called `aws_creds` which forces re-login.
