### ISSUE TITLE
Auto switch role if I click on a link which refer to a different account  

### ISSUE THREAD

**Issue by andreaskemvise** [tilfin/aws-extend-switch-roles#83]
If I click on the details link in my pipeline console with a cloudformation provider, I want to switch to the directly to target account. 

The link targeting to:
 https://eu-central-1.console.aws.amazon.com/cloudformation/home?#/changeset/detail?changeSetId=arn:aws:cloudformation:eu-central-1:{AccountID}:changeSet/changeset/e28dffd1-e857-41cc-84b0-6d71xxxxxxxxx
<img width="309" alt="Bildschirmfoto 2019-03-26 um 13 43 08" src="https://user-images.githubusercontent.com/44567897/54998038-7026ed00-4fcd-11e9-9b30-c0fb97a93d1b.png">

Is this possible?

**Comment by jmporchet** [comment]
Do not use this extension right now!!
https://github.com/tilfin/aws-extend-switch-roles/commit/dca1764c4bb7830ff9ed97232741180f15f861ff
These URLs redirect to a fishing site!

**Comment by tilfin** [comment]
This extension will not interfere with the content of the console, except for the navigation.
