### ISSUE TITLE
Extention / owner github account is compromised!

### ISSUE THREAD

**Issue by jmporchet** [tilfin/aws-extend-switch-roles#86]
This commit introduced several fishing sites in the code, that will leak your credentials to an attacker https://github.com/tilfin/aws-extend-switch-roles/commit/dca1764c4bb7830ff9ed97232741180f15f861ff

**Comment by JoostSaanen** [comment]
@tilfin Could you explain this commit?

**Comment by tilfin** [comment]
@jmporchet The `amazonaws-us-gov.com` domain is not for fishing. 
Please see _Q: How do I sign into the Management Console?_  at https://aws.amazon.com/console/faqs/?nc1=h_ls

**Comment by tilfin** [comment]
Recently, the AWS Gov console also supported switch menu, so I did it. #75 #84 
https://aws.amazon.com/about-aws/whats-new/2019/02/switch-role-in-govcloud/?nc1=h_ls

**Comment by jmporchet** [comment]
That's right, I was a bit overzealous/too fast in my analysis.
@JoostSaanen is right too.

Sorry about that 🙏
