### ISSUE TITLE
Image is tiny beside the role name

### ISSUE THREAD

**Issue by arsirantala** [tilfin/aws-extend-switch-roles#87]
Is it possible to extend the space used for the drop down list to accommodate little bit more space for role's image?

I tried different sizes of the image and it would seem that the image is always scaled down to match width and height which I was not able to figure out - making the image unreadable.

I used this site: https://imgplaceholder.com/ to create a image containing two letters. I used sizes like 100 x 100 and tuned the size all way to 24 x 24, and despite the fact the image looked good in the said site, plugin rendered it to so small (even with 24x24) that I wasn't able to read whats in the image anymore.

**Comment by tilfin** [comment]
Originally this feature was added from PR, and I didn't mean that I was actively implementing it. But I released it because this feature itself does not affect the others.

You may struggle to identify the icon If your monitor is not retina display. I think they are tiny too, so If there is a good solution with CSS, I am trying to fix it.

**Comment by arsirantala** [comment]
Would be nice if the size of the image beside role would be globally set from preferences of this addon.

**Comment by arsirantala** [comment]
> Originally this feature was added from PR, and I didn't mean that I was actively implementing it. But I released it because this feature itself does not affect the others.
> 
> You may struggle to identify the icon If your monitor is not retina display. I think they are tiny too, so If there is a good solution with CSS, I am trying to fix it.

I am using 4k display with my mac (using 3.4k x 1.4k resolution).

**Comment by tilfin** [comment]
I enlarged profile icon a little, It's difficult to do more than this.
