### ISSUE TITLE
Sync config file across devices (Chrome & Firefox)

### ISSUE THREAD

**Issue by z0ph** [tilfin/aws-extend-switch-roles#88]
Hi,

It would be very nice if we could sync the config file using Chrome Sync or Firefox Sync across multiple devices: laptop @ home and laptop @ work.

Thanks!

**Comment by tilfin** [comment]
@z0ph Your setting is synchronized if you sign in to the both browsers with the same chrome / firefox user.

**Comment by z0ph** [comment]
I'm sign-in with the same account and no, I've to copy past my settings across browsers. (Chrome to Chrome and Firefox to Firefox). Did I miss something?

**Comment by tilfin** [comment]
@z0ph Is the item for the extension turned on in your `chrome://settings/syncSetup/advanced` ?

**Comment by z0ph** [comment]
Yes,
![image](https://user-images.githubusercontent.com/20846187/57129114-c2f68000-6d95-11e9-9a31-8b68a6062804.png)

**Comment by z0ph** [comment]
On both computers.

**Comment by tilfin** [comment]
It turned out that the settings displayed in the textarea were not synchronized. However, the actual profile settings were synchronized on background.
