### ISSUE TITLE
more than 200 roles please?

### ISSUE THREAD

**Issue by thomasrawley** [tilfin/aws-extend-switch-roles#94]
Why the limit?

**Comment by tilfin** [comment]
Because of the storage restriction on browser sync feature. I have already managed to increase this number by the compression.

**Comment by roboweaver** [comment]
Same issue - limit of 200 is causing me pain, maybe update to use an endpoint or s3 bucket to store the list ?

**Comment by tilfin** [comment]
@roboweaver You can choose **Local** storage.
