### ISSUE TITLE
As a user I would like to set my custom display name so that I can recognize roles easier

### ISSUE THREAD

**Issue by MWeesenaar** [tilfin/aws-extend-switch-roles#95]
**User story:** 
As a user I would like to set my custom display name so that I can recognize roles easier

**Description:**
When you manually switch a role, AWS console allows you to set a custom display name. Currently the code does this by concat'ing ${role_name}@${account_id}. I disabled the visibility accountId, since that does not tell me much (as a person); so now I only see the role name. However, due to the way things are set up at our project; we have overlapping role names. Therefore I would like to be able to set a custom name, so it's more clear to me to which role I am switching.

I would suggest to add a field to the configuration (e.g.: display_name=foo), which will be visible as display name - but only if it is set. Otherwise, fallback to the default behaviour: ${role_name}[@${account_id}].

If preferred, I could have a look at the code and make a suggestion - however, if you guys think its better / easier to include it by yourselves; please feel free to do so. :-)

**Comment by tilfin** [comment]
The profile name should be displayed as it.

**Comment by MWeesenaar** [comment]
Sorry for the late response, and I have been quite stupid... So sorry that I raised this issue, whilst I just overlooked it. 
Thank you for your awesome plugin :-)
